FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ src/
COPY monitoring/ monitoring/
COPY data/ data/

ENV MLFLOW_TRACKING_URI=http://mlflow:5000

WORKDIR /app/monitoring
CMD ["streamlit", "run", "dashboard.py", "--server.address=0.0.0.0", "--server.port=8501"]
