FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ src/
COPY monitoring/drift_detector.py monitoring/drift_detector.py
COPY api/ api/
COPY data/ data/

ENV MLFLOW_TRACKING_URI=http://mlflow:5000
ENV PYTHONPATH=/app/src

WORKDIR /app/api
CMD ["uvicorn", "serve:app", "--host", "0.0.0.0", "--port", "8000"]
